sudo: required
services:
  - docker

before_install:
  - docker build -t dineshtailor/react-test -f client/Dockerfile.dev ./client

script:
  - docker run dineshtailor/react-test npm run test -- --coverage
after_success:
  - docker build -t dineshtailor/multi-client ./client
  - docker build -t dineshtailor/multi-nginx ./nginx
  - docker build -t dineshtailor/multi-server ./server
  - docker build -t dineshtailor/multi-worker ./worker
        #login into docker client
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dineshtailor/multi-client
  - docker push dineshtailor/multi-nginx
  - docker push dineshtailor/multi-server
  - docker push dineshtailor/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-686465145436"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY
